channels:
  - conda-forge
dependencies:
  - r-base=4.0
  - r-learnr
  - r-gplots
  - r-rcolorbrewer
  - r-nmf
  - r-biasedurn
  - bioconductor-limma
  - bioconductor-edger
  - bioconductor-glimma
  - bioconductor-org.mm.eg.db
  - bioconductor-go.db
