#!/bin/bash

# stop build if error
set -e 

# install gradethis from GitHub as not in CRAN yet
Rscript -e "remotes::install_github('rstudio-education/gradethis')"

# create file containing all learnr challenges
cat challenge*/challenge{1..12}.Rmd >> challenges_all/challenges_all.Rmd