---
output: 
  html_document
runtime: shiny_prerendered
---

```{r setup2, include=FALSE}
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(limma)
library(RColorBrewer)
```

```{r}
if(!exists("sampleinfo")) {
    load("../data/data.Rdata")
}
```

### Challenge 2

1. Redo the plots with the colours for status (lactate, pregnant, virgin): `brewer.pal(3,"Dark2")`
2. Change the plotting characters to symbols, such that basal samples have the value `1` and luminal samples have the value `4`. HINT: use `pch` argument.
3. Add a legend for status at the top left and for cell type at the bottom.

```{r challenge2, exercise=TRUE}
# Get some nicer colours from brewer pal, using the "Dark2" palette.
cols <- brewer.pal(3,"Dark2")
col.status <- ____
char.celltype <- ____
plotMDS(y, col=____, pch=___, cex=2)
legend("topleft",____)
legend("bottom", ____)
```

```{r, challenge2-solution, exercise.reveal_solution = FALSE}
cols <- brewer.pal(3,"Dark2")
char.celltype <- c(1,4)[sampleinfo$CellType]
col.status <- cols[factor(sampleinfo$Status)]
plotMDS(y,col=col.status,pch=char.celltype,cex=2)
legend("topleft",legend=levels(sampleinfo$Status),col=cols,pch=16)
legend("bottom",legend=levels(sampleinfo$CellType),pch=c(1,4))
```


```{r challenge2-code-check}
grade_this_code()
```

<br>

